name: Deploy Docs

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'        # Triggers on any change inside the docs folder
      - 'mkdocs.yml'     # Triggers on changes to yml files in config
      - '.github/workflows/**'
      - '!README.md'     # Excludes changes to this specific file
    branches:
      - main

permissions:
  contents: read
  id-token: write
  pages: write

# Allow only one concurrent deployment
concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: 'pip' # caching pip dependencies

      - name: 'Installing dependencies'
        run: pip install -r requirements.txt

      - name: 'Building site'
        run: mkdocs build -f mkdocs.yml
        env:
          MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Fix permissions'
        run: |
          chmod -c -R +rX "site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: 'Archive artifact'
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "site/" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            .
        env:
          INPUT_PATH: site/

      - name: 'Upload artifact'
        uses: actions/upload-artifact@v6
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1
          if-no-files-found: error

      - name: 'Deploy to GitHub Pages'
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GITHUB_TOKEN }}
